### PR TITLE
Listing files within azure storage and Windows support!

### PR DESCRIPTION
**Pull request by jmularski**
Added ability to list files on azure storage as well as Windows docker support! Anybody from mentors could review and merge? Also corrected minor error on README.md

### CODE REVIEW

**Comment by jmularski** [comment]
Should be ok now

**Comment by jmularski** [comment]
You can still escape the quotes, but I don't think anybody would do that without wanting to specifically break the code.

**Comment by jmularski** [comment]
@lasitha-petthawadu Can you have another look?

**Comment by lasitha-petthawadu** [comment]
@jmularski This is acceptable, merging the PR

**Comment by bauripalash** [comment]
What about the syntax `clocal storage query "$query_syntax"` mentioned in Code-in task details , where `query_syntax` would be `ls` and `ls <filename>`

**Pull request merged**
